{{- if .Values.customConfig.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgadmin.fullname" . }}-custom-settings
data:
  config_local.py: | {{ .Values.customConfig.config| nindent 4 }}
{{- end -}}